dataset: "2D_denoising"
data:
    image_size: 128
    channels: 1
    noise: False
    train_batch: 64
    val_batch: 16
    data_dir: "/bigdata/casus/MLID/RuiLi/Data/LM/bcr_application/CARE_data/processed/2D_denoising/"

model:
    type: "2D_denoising"
    in_ch: 1
    out_ch: 1
    Nrho: 128
    Ntheta: 128

training:
    NUM_STEPS: 2000
    best_val_loss: 'inf'
    patience: 10 
    opti: 'adam'
    lr: 0.001
    ckpt_path: './checkpoint/2D_denoising/'
    save_freq: 50
    val_freq: 100
